movie/urls.py
from django.urls import path
from . import views

app_name = 'movie'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('random-movies/', views.MoviesListView.as_view(), name='random_movies'),
    path('genres/<int:pk>/movies/', views.MoviesGenreView.as_view(), name='movies_genre'),
    path('actors/<int:pk>/movies/', views.MoviesActorView.as_view(), name='movies_actor'),
    path('countries/<int:pk>/movies/', views.MoviesCountryView.as_view(), name='movies_country'),
    path('full-categories/', views.MoviesFullCategoriesView.as_view(), name='full_categories'),
    path('full-categories/<int:pk>/', views.MoviesCategoryView.as_view(), name='movies_category'),
    path('movies/<int:pk>/', views.MovieDetailView.as_view(), name='movie'),
    path('add-review/<int:pk>/', views.AddReviewView.as_view(), name='add_review'),
    path('add-rating/', views.AddRatingView.as_view(), name='add_rating'),
    path('search/', views.search, name='search'),
    path('fav/<int:pk>/', views.favorite_add, name='favorite_add'),
    path('favorites/', views.favorite_list, name='favorite_list'),
]

movielab/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('djmaster/', admin.site.urls),
    path('', include('movie.urls')),
    path('user/', include('user.urls')),
    path('polls/', include('polls.urls')),
    path('forming/', include('forming.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = error_404_view

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('',  views.HomeView.as_view(), name='home'),
    path('<int:pk>/', views.DetailedView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultView.as_view(), name='results'),
    path('<int:question_id>/vote', views.vote, name='vote'),
]

user/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='user/password-reset-form.html',
        email_template_name='user/password-reset-email.html',
        success_url=reverse_lazy('user:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password-reset-done.html'), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='user/password-reset-confirm.html',
        success_url=reverse_lazy('user:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='user/password-reset-complete.html'), name='password_reset_complete'),
]

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200, verbose_name='Вопрос')
    pub_date = models.DateTimeField(verbose_name='Дата публикации')
    is_publish = models.BooleanField(verbose_name='Опубликовано', default=True)

    def __str__(self):
        return f'{self.question_text} {self.pub_date.strftime("%m-%d-%Y %H:%M")} {self.is_publish}'


class Choice(models.Model):
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    choice_text = models.TextField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.choice_text} {self.votes}'

polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views.generic import ListView, DetailView

from .models import *


class HomeView(ListView):
    template_name = 'polls/home.html'
    context_object_name = 'question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now(), is_publish=True).order_by('-pub_date')


class DetailedView(DetailView):
    model = Question
    template_name = 'polls/detail.html'
    context_object_name = 'question'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now(), is_publish=True)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'Выберите ответ'
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class ResultView(DetailedView):
    model = Question
    template_name = 'polls/result.html'
    context_object_name = 'question'

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Проголосовать">
    </form>
</body>
</html>

polls/templates/polls/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if question_list %}
        {% for question in question_list %}
        <ul>
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        </ul>
        {% endfor %}
    {% else %}
        <p>К сожалению записо не были найдены</p>
    {% endif %}
</body>
</html>

polls/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_title }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} votes{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
</body>
</html>