movielab/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('djmaster/', admin.site.urls),
    path('', include('movie.urls')),
    path('user/', include('user.urls')),
    path('polls/', include('polls.urls')),
    path('forming/', include('forming.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = error_404_view

user/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='user/password-reset-form.html',
        email_template_name='user/password-reset-email.html',
        success_url=reverse_lazy('user:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password-reset-done.html'), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='user/password-reset-confirm.html',
        success_url=reverse_lazy('user:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='user/password-reset-complete.html'), name='password_reset_complete'),
]

user/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(default='default_user.png', upload_to='profile')

    def __str__(self):
        return f'{self.user}'

user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetConfirmView

from .models import Profile


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Логин'}))
    email = forms.CharField(label='E-mail', widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'E-mail'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Пароль'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Повтор пароля'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean(self):
        cleaned_data = self.cleaned_data
        msg_email = "Эта почта уже зарегестрированна"
        msg_user = "Пользователь с таким именем уже существует"
        if User.objects.filter(email=cleaned_data.get('email')).exists():
            self._errors['email'] = self.error_class([msg_email])
        elif User.objects.filter(username=cleaned_data.get('username')).exists():
            self._errors['username'] = self.error_class([msg_user])

            del cleaned_data['email']
            del cleaned_data['username']
        return cleaned_data


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Логин'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}))


class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Логин'}))
    email = forms.CharField(label='E-mail', widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'E-mail'}))

    class Meta:
        model = User
        fields = ('username', 'email')


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('photo',)

user/views.py
from smtplib import SMTPDataError
from urllib import request

from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, TemplateView

from .forms import RegisterUserForm, LoginUserForm, ProfileUpdateForm, UserUpdateForm

from django.contrib import messages

from .models import Profile
from .tokens import account_activation_token
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import send_mail
from django.conf import settings
from django.utils.html import format_html


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(request, user)
        messages.success(request, "Спасибо за подтверждение по электронной почте. Теперь вы успешно авторизованы.")
        Profile.objects.create(user_id=request.user.id)
        #return redirect('movie:home')
    else:
        messages.error(request, format_html("Ссылка активации недействительна! Если Вы не успели активировать учетную запись по ссылке, воспользуйтесь формой восстановления доступа. Для этого нажмите на <a href='/reactivation.html' class='alert-link'>ссылку</a>."))

    return redirect('movie:home')


def activateEmail(request, user, to_email):
    subject = "Активируйте свою учетную запись пользователя."
    context = {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        "protocol": 'https' if request.is_secure() else 'http',
    }
    text = render_to_string("user/template_activate_account.html", context)
    html = render_to_string("user/template_activate_account.html", context)

    send_mail(subject, message=text, html_message=html, from_email=settings.EMAIL_HOST_USER, recipient_list=[to_email], fail_silently=False)


def register(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active=False
            user.save()
            try:
                activateEmail(request, user, form.cleaned_data.get('email'))
                messages.success(request, 'На указанный адрес электронной почты придет письмо активации учетной записи. Для завершения регистрации перейдите по ссылке в письме.')
                return redirect('movie:home')
            except SMTPDataError:
                form.add_error('email', 'Ошибка электронной почты')
            except Exception as error:
                HttpResponse(f'Ошибка: {error}')

        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    else:
        form = RegisterUserForm()

    return render(
        request=request,
        template_name="user/register.html",
        context={"form": form}
        )


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'user/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        return next_url if next_url else reverse_lazy('movie:home')


def logout_user(request):
    logout(request)
    return redirect('user:login')


class ProfileView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'user/profile.html'
    context_object_name = 'profile'
    login_url = 'user:login'

    def get_queryset(self):
        return Profile.objects.get(user_id=self.request.user)


class ProfileEditView(LoginRequiredMixin, TemplateView):
    user_form = UserUpdateForm
    profile_form = ProfileUpdateForm
    template_name = 'user/profile-edit.html'
    login_url = 'user:login'

    def post(self, request):
        post_date = request.POST or None
        file_data = request.FILES or None
        user_form = UserUpdateForm(post_date, instance=request.user)
        profile_form = ProfileUpdateForm(post_date, file_data, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('user:profile')

        context = self.get_context_data(user_form=user_form, profile_form=profile_form)

        return self.render_to_response(context)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

user/templates/user/login.html
{% extends 'movie/base.html' %}
{% load static %}

{% block content %}
<div class="login-form__wrapper">
  <div class="login-form">
    <div class="big-logo"><a class="logo"><img class="logo__img" src="{% static 'images/logo.png'%}" alert="logo">MovieLab</a></div>
      {% for error in form.non_field_errors %}
      <p class="text-danger mb-4">{{ error }}</p>
      {% endfor %}
    <form class="login-form__form" method="post">
        {% csrf_token %}
        {% for el in form %}
            <p class="form-item">
                {{ el }}
                <small class="form-text text-danger">{{ el.errors }}</small>
            </p>
        {% endfor %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <a class="form-item text_yellow text_right" href="{% url 'user:password_reset' %}">Забыли пароль?</a>
        <button class="form-item btn btn_yellow" type="submit">Войти</button>
      <p class="form-item">Или</p><a href="#" class="form-item btn btn_vk_blue">Войти через Вконтакте</a>
      <p class="form-item login-form__btn-list"><a href="#" class="btn btn_ok">Ok</a><a href="#" class="btn btn_mail">Mail</a></p>
      <p class="form-item">Нет аккаунта? <a class="text_yellow" href="{% url 'user:register' %}">Регистрация</a></p>
    </form>
  </div>
</div>
{% endblock%}

user/templates/user/password-reset-complete.html
{% extends 'movie/base.html' %}
{% load static %}

{% block content %}
 <main class="main">
  <div class="container-full">
    <div class="password-reset__wrapper">
      <div class="password-reset">
        <h4 class="alert-heading">Сброс пароля</h4>
        <p class="mb-4">Ваш пароль установлен. Теперь вы можете <a href="{% url 'user:login' %}">войти</a> в систему.</p>
      </div>
    </div>
  </div>
</main>
{% endblock%}

user/templates/user/password-reset-confirm.html
{% extends 'movie/base.html' %}
{% load static %}

{% block content %}
<main class="main">
  <div class="container-full">
    <div class="password-reset__wrapper">
        {% if validlink %}
          <div class="password-reset">
            <h4 class="alert-heading">Подтверждение сброса пароля</h4>
            <p class="mb-4">Пожалуйста, дважды введите новый пароль, чтобы мы могли убедиться, что вы ввели его правильно.</p>
            <form method="post">
                {% csrf_token %}
              <p class="form-input mb-4">
                  <input class="form-control" type="password" name="new_password1" autocomplete="new-password" id="id_new_password1" required="" placeholder="Новый пароль">
              </p>
              <p class="form-input mb-4">
                  <input class="form-control" type="password" name="new_password2" autocomplete="new-password" id="id_new_password2" required="" placeholder="Подтвердите пароль">
              </p>
                {% for field, errors in form.errors.items %}
                    <p>
                        {% for error in errors %}
                             <small class="form-text text_danger">{{ error }}</small>
                        {% endfor %}
                    </p>
                {% endfor %}
                <button class="btn btn_yellow" type="submit">Изменить мой пароль</button>
            </form>
              {% else %}
              <p class="mb-4">
                  Ссылка для сброса пароля недействительна, возможно, потому, что она уже использовалась.<br><br>
                  Запросите новый <a href="{% url 'user:password_reset' %}">сброс пароля</a>.
              </p>
          </div>
        {% endif %}
    </div>
  </div>
</main>
{% endblock%}

user/templates/user/password-reset-done.html
{% extends 'movie/base.html' %}
{% load static %}

{% block content %}
<main class="main">
  <div class="container-full">
    <div class="password-reset__wrapper">
      <div class="password-reset">
        <h4 class="alert-heading">Сброс пароля</h4>
        <p class="mb-4">Мы отправили вам по электронной почте инструкции по установке пароля, если существует учетная запись с указанным вами адресом электронной почты. Вы должны получить их в ближайшее время.</p>
        <hr>
        <p>Если вы не получили электронное письмо, убедитесь, что вы ввели адрес, который вы указали при регистрации, и проверьте папку со спамом</p>
      </div>
    </div>
  </div>
</main>
{% endblock%}

user/templates/user/password-reset-email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

user/templates/user/password-reset-form.html
{% extends 'movie/base.html' %}
{% load static %}

{% block content %}
<main class="main">
  <div class="container-full">
    <div class="password-reset__wrapper">
      <div class="password-reset">
        <h4 class="alert-heading">Сброс пароля</h4>
        <p class="mb-4">Забыли пароль? Введите свой адрес электронной почты ниже, и мы вышлем инструкции по настройке нового адреса электронной почты.</p>
           <small class="form-text text-danger">{{ form.non_field_errors }}</small>
        <form method="post">
            {% csrf_token %}
            <p class="form-input mb-4">
                <input class="form-control" type="email" name="email" placeholder="Адрес электронной почты:" required="">
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <small class="form-text text_danger">{{ error }}</small>
                    {% endfor %}
                {% endfor %}
            </p>
            <button class="btn btn_yellow" type="submit">Сбросить пароль</button>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock%}

user/templates/user/profile-edit.html
{% extends 'movie/base.html' %}
{% load static %}

{% block content %}
<main class="main">
  <div class="container-full">
    <div class="profile">
      <div class="profile__head">
          <a class="profile__support text_yellow hide_sm" href="#">Связаться с поддержкой</a>
          <a class="logout btn btn_yellow" href="{% url 'user:logout' %}">Выйти</a>
      </div>
      <div class="profile__main">
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
          <div class="profile__photo">
              <img id="uploadPreview" src="{{ request.user.profile.photo.url }}" alert="logo">
          </div>
          <p class="form-item">
              <label class="input-file">
                  <input id="uploadImage" type="file" name="photo" accept="image/*" onchange="PreviewImage();">
                  <span>Выберите файл</span>
              </label>
          </p>
            {% for el in user_form %}
                <p class="form-item">
                    {{ el }}
                     <small class="text_danger">{{ el.errors }}</small>
                </p>
            {% endfor %}
            <button type="submit" class="form-item btn btn_yellow">Сохранить изменения</button>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock%}

user/templates/user/profile.html
{% extends 'movie/base.html' %}
{% load static %}

{% block content %}
<main class="main">
  <div class="container-full">
    <div class="profile">
      <div class="profile__head">
          <a class="profile__support text_yellow hide_sm" href="#">Связаться с поддержкой</a>
          <a class="logout btn btn_yellow" href="{% url 'user:logout' %}">Выйти</a>
      </div>
      <div class="profile__main">
        <div class="profile__photo">
            <img src="{{ profile.photo.url }}" alt="{{ profile.user }}" alert="logo">
        </div>
        <h2 class="profile__name">{{ profile.user }}</h2>
          <a class="profile__edit-btn btn_white" href="{% url 'user:profile_edit' %}">Изменить профиль</a>
          <a class="profile__history-clean btn_yellow" href="#">Очистить историю просмотра</a>
          <a class="profile__compact text_yellow" href="#">Пользовательское соглашение</a>
          <a class="profile__support text_yellow show_sm" href="#">Связаться с поддержкой</a>
      </div>
    </div>
  </div>
</main>
{% endblock%}

user/templates/user/register.html
{% extends 'movie/base.html' %}
{% load static %}

{% block content %}
<main class="main">
  <div class="container-full">
    <div class="register__wrapper">
      <div class="register">
        <h2>Регистрация</h2>
       <form method="post">
           {% csrf_token %}
           {% for field in form %}
              <p class="form-input mb-4">
                  {{ field }}
                    {% if field.help_text %}
                        <small class="form-text text_danger" style="display: none ">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
              </p>
           {% endfor %}
          <button class="btn btn_yellow" type="submit">Регистрация</button>
          <p>Уже есть аккаунт? <a class="text_yellow" href="{% url 'user:login' %}" ">Войти</a></p>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock%}

user/templates/user/template_activate_account.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
</head>
<body>
    {% autoescape off %}
    <b>Здравствуйте {{ user }}!</b><br>
    <p>Вы получили это письмо, так как зарегестрировались на {{ domain }}.</p>

    Для активации Вашей учетной записи перейдите по: <a href="{{ protocol }}://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}">ссылке</a><br><br>
    Ссылка действительна в течении 4-x часов с момента получения письма. <br><br>
    Если вы не регестрировались, просто проигнорируйте это письмо. <br><br>
    Спасибо!

    {% endautoescape %}
</body>
</html>