movie/urls.py
from django.urls import path
from . import views

app_name = 'movie'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('random-movies/', views.MoviesListView.as_view(), name='random_movies'),
    path('genres/<int:pk>/movies/', views.MoviesGenreView.as_view(), name='movies_genre'),
    path('actors/<int:pk>/movies/', views.MoviesActorView.as_view(), name='movies_actor'),
    path('countries/<int:pk>/movies/', views.MoviesCountryView.as_view(), name='movies_country'),
    path('full-categories/', views.MoviesFullCategoriesView.as_view(), name='full_categories'),
    path('full-categories/<int:pk>/', views.MoviesCategoryView.as_view(), name='movies_category'),
    path('movies/<int:pk>/', views.MovieDetailView.as_view(), name='movie'),
    path('add-review/<int:pk>/', views.AddReviewView.as_view(), name='add_review'),
    path('add-rating/', views.AddRatingView.as_view(), name='add_rating'),
    path('search/', views.search, name='search'),
    path('fav/<int:pk>/', views.favorite_add, name='favorite_add'),
    path('favorites/', views.favorite_list, name='favorite_list'),
]

movielab/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('djmaster/', admin.site.urls),
    path('', include('movie.urls')),
    path('user/', include('user.urls')),
    path('polls/', include('polls.urls')),
    path('forming/', include('forming.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = error_404_view

user/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='user/password-reset-form.html',
        email_template_name='user/password-reset-email.html',
        success_url=reverse_lazy('user:password_reset_done')
    ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='user/password-reset-done.html'), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='user/password-reset-confirm.html',
        success_url=reverse_lazy('user:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='user/password-reset-complete.html'), name='password_reset_complete'),
]

movie/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator, MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse


class Movie(models.Model):
    """ Фильм """
    QUALITY = [
        ('HD', 'HD'),
    ]
    TYPE = [
        ('FILM', 'FILM'),
    ]
    title = models.CharField(max_length=100, verbose_name='Название')
    slug = models.SlugField(
        max_length=255,
        db_index=True,
        verbose_name="URL",
        unique=True,
        blank=True
    )
    description = models.TextField(
        max_length=1000,
        verbose_name='Описание',
        blank=True
    )
    year = models.CharField(
        verbose_name='Год',
        max_length=4,
        validators=[RegexValidator(r'19|20\d{2}')]
    )
    rating = models.CharField(
        verbose_name='Рейтинг',
        max_length=4,
        blank=True
    )
    poster_url_preview = models.ImageField(
        upload_to='posters-preview',
        verbose_name='Изображение постера (preview)',
        blank=True
    )
    poster_url = models.ImageField(
        upload_to='posters',
        verbose_name='Изображение постера',
        blank=True
    )
    video = models.FileField(
        upload_to='video',
        verbose_name='Загрузить видео',
        blank=True
    )
    quality = models.CharField(
        max_length=2,
        choices=QUALITY,
        verbose_name='Качество',
        default='HD',
        blank=True
    )
    type = models.CharField(
        max_length=30,
        choices=TYPE,
        verbose_name='Тип',
        blank=True
    )
    film_length = models.CharField(
        max_length=3,
        verbose_name='Продолжительность',
        blank=True
    )
    countries = models.ManyToManyField('Country', verbose_name='Страна', blank=True)
    genres = models.ManyToManyField('Genre', verbose_name='Жанры', blank=True)
    actors = models.ManyToManyField('Actor', verbose_name='Актёр', blank=True)
    directors = models.ManyToManyField('Director', verbose_name='Режисёр', blank=True)
    categories = models.ManyToManyField('Category', verbose_name='Категория', blank=True, default='')
    is_publish = models.BooleanField(default=True, verbose_name='Опубликовано')
    favorites = models.ManyToManyField(User, related_name='favorite', default=None, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'
        unique_together = ('title', 'year')


class Reviews(models.Model):
    """ Комментарий """
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE, verbose_name='Фильм', related_name='reviews_movie', blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', blank=True, null=True)
    text_review = models.TextField(verbose_name='Отзыв',  max_length=200)
    create_data = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False, verbose_name='Опубликован')

    def __str__(self):
        return f'{self.movie}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class Genre(models.Model):
    """ Жанр """
    genre = models.CharField(max_length=30, verbose_name='Жанр')
    is_publish = models.BooleanField(default=True, verbose_name='Опубликовано')

    def __str__(self):
        return self.genre

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'


class Actor(models.Model):
    """ Актер """
    actor = models.CharField(max_length=50, verbose_name='Актер')

    class Meta:
        verbose_name = 'Актер'
        verbose_name_plural = 'Актеры'

    def __str__(self):
        return self.actor


class Director(models.Model):
    """ Режисёр """
    director = models.CharField(max_length=50, unique=True, verbose_name='Режисёр')

    def __str__(self):
        return self.director

    class Meta:
        verbose_name = 'Режисёр'
        verbose_name_plural = 'Режисёры'


class Country(models.Model):
    """ Страна """
    country = models.CharField(max_length=50, verbose_name='Страна', unique=True)

    def __str__(self):
        return self.country

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'


class Category(models.Model):
    category = models.CharField(max_length=60, verbose_name='Категория', default='')
    is_publish = models.BooleanField(default=True, verbose_name='Опубликовано')
    poster = models.FileField(
        upload_to='posters-category',
        verbose_name='Загрузить preview',
        blank=True
    )

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class RatingView(models.Model):
    STARS = ((num, f'{num}') for num in range(0, 11))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey('Movie', on_delete=models.CASCADE)
    star = models.PositiveSmallIntegerField(default=0, validators=[
        MinValueValidator(0), MaxValueValidator(10)
    ], choices=STARS)

    def __str__(self):
        return f'{self.movie}'

movie/forms.py
from django import forms
from .models import Reviews, RatingView


class ReviewForm(forms.ModelForm):
    text_review = forms.CharField(widget=forms.Textarea(
        attrs={
            'placeholder': 'Оставьте отзыв',
            'class': 'form-input'
        }))

    class Meta:
        model = Reviews
        fields = ('text_review',)


class RatingForm(forms.ModelForm):
    choices = [num for num in range(1, 11)]
    star = forms.ChoiceField(widget=forms.RadioSelect(), choices=choices, required=False)

    class Meta:
        model = RatingView
        fields = ('star',)

movie/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from .forms import ReviewForm, RatingForm

from .models import *


class MoviesListView(ListView):
    """ Список Фильмов """
    model = Movie
    template_name = 'movie/movies-list.html'
    context_object_name = 'movies'
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Movilab'
        context['movies'] = Movie.objects.filter(is_publish=True)[:40]  # Сделать Рандомный фильтр
        return context


class MoviesFullCategoriesView(ListView):
    """ Категории фильмов """
    model = Category
    template_name = 'movie/full-categories.html'
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Коллекции'
        context['categories'] = Category.objects.filter(is_publish=True)
        return context


class MoviesCategoryView(MoviesListView):
    """ Список фильмов в соответствии с категорией """
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movies'] = Movie.objects.filter(categories__pk=self.kwargs['pk'], is_publish=True)
        return context


class MoviesGenreView(MoviesListView):
    """ Список Фильмов в соответствии с жанром """
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movies'] = Movie.objects.filter(genres__pk=self.kwargs['pk'], is_publish=True)
        return context


class MoviesActorView(MoviesListView):
    """ Список Фильмов. Фильтр по Актерам """
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movies'] = Movie.objects.filter(actors__pk=self.kwargs['pk'], is_publish=True)
        return context


class MoviesCountryView(MoviesListView):
    """ Список Фильмов. Фильтр по Странам """
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movies'] = Movie.objects.filter(countries__pk=self.kwargs['pk'], is_publish=True)
        return context


class MovieDetailView(DetailView):
    """ Фильм """
    model = Movie
    template_name = 'movie/movie.html'
    context_object_name = 'movie'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['actors'] = context['movie'].actors.all()[:14]
        context['countries'] = context['movie'].countries.all()
        context['genres'] = context['movie'].genres.all()
        context['directors'] = context['movie'].directors.all()
        context['fav'] = context['movie'].favorites.filter(pk=self.request.user.id)
        context['reviews'] = context['movie'].reviews_movie.all()  # filter(status=True)
        context['star_form'] = RatingForm()
        star_checked = RatingView.objects.filter(movie_id=self.kwargs['pk'], user_id=self.request.user.id)
        if star_checked.exists():
            context['star_checked'] = star_checked[0]
        return context


class HomeView(ListView):
    model = Movie
    template_name = 'movie/index.html'
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        cats = Category.objects.filter(is_publish=True)
        context['title'] = 'Movilab'
        context['movies'] = {k: Movie.objects.filter(categories=k) for k in cats}
        context['genres'] = Genre.objects.filter(is_publish=True)
        
        return context


def search(request):
    msg = " ".join(request.GET['q'].split())
    movies = Movie.objects.filter(title__iregex=rf'^{msg}|\s{msg}')
    
    context = {
        'movies': movies,
    }
    if movies and len(msg) > 1:
        return render(request, 'movie/search.html', context=context)
    else:
        return render(request, 'movie/page-error.html', context=context)


def favorite_list(request):
    if request.user.is_authenticated:
        new = Movie.objects.filter(favorites=request.user)
        return render(request, 'movie/favorites.html', {'new': new})
    else:
        return  render(request, 'movie/favorites.html', {})


@login_required
def favorite_add(request, pk):
    movie = get_object_or_404(Movie, id=pk)
    if movie.favorites.filter(id=request.user.id).exists():
        movie.favorites.remove(request.user)
    else:
        movie.favorites.add(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


class AddReviewView(View):
    
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.movie = movie
            form.user_id = request.user.id
            form.save()
        return redirect('movie:movie', movie.pk)


class AddRatingView(View):
    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            RatingView.objects.update_or_create(
                movie_id=int(request.POST.get("movie")),
                defaults={'star': int(request.POST.get("radio"))},
                user_id=request.user.id,
            )

            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)



movie/templates/movie/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title|capfirst }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script defer="defer" src="{% static 'js/index.js' %}"></script>

</head>
<body>
    <header class="header">
       <a class="logo header__logo" href="{% url 'movie:home' %}"><img class="logo__img" src="{% static 'images/logo.png' %}" alert="logo">MovieLab</a>
       <div class="header__links">
          <a class="nav-link active" href="{% url 'movie:full_categories' %}">
             <span class="icon icon_catalog">
                <svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" mirror-in-rtl="true">
                   <path fill="#494c4e" d="M6 18H1a1 1 0 0 1-1-1v-5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1zM17 18h-5a1 1 0 0 1-1-1v-5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1zM6 7H1a1 1 0 0 1-1-1V1a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1zM17.708 5.24l-3.535 3.535a1 1 0 0 1-1.414 0L9.224 5.24a1 1 0 0 1 0-1.413L12.76.292a1 1 0 0 1 1.414 0l3.535 3.535a1 1 0 0 1-.002 1.414z"/>
                </svg>
             </span>
             <span>Каталог</span>
          </a>
          <a class="nav-link" href="{% url 'movie:favorite_list' %}">
             <span class="icon">
                <svg fill="#494c4e" width="20px" height="20px" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMin" class="jam jam-screen-f">
                   <path d="M3 .565h14a3 3 0 0 1 3 3v9a3 3 0 0 1-3 3H3a3 3 0 0 1-3-3v-9a3 3 0 0 1 3-3zm4 16h6a1 1 0 0 1 0 2H7a1 1 0 0 1 0-2z"/>
                </svg>
             </span>
             <span>Мой MovieLab</span>
          </a>
       </div>
       <div class="header__search">
          <form class="form-search" action="{% url 'movie:search' %}" method="get">
              <input class="form-search__input" name="q" type="search" placeholder="Поиск по фильмам и сериалам">
          </form>
       </div>
       <div class="header__apps">
          <a class="btn app-link">
             <span class="icon icon_android">
                <svg width="24px" height="24px" viewBox="0 0 18 18" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                   <path d="M3.809 5.696h9.383v6.807c0 0.623-0.502 1.125-1.113 1.125h-0.769v2.32c0 0.583-0.469 1.052-1.051 1.052-0.583 0-1.055-0.47-1.055-1.052v-2.32h-1.408v2.32c0 0.582-0.472 1.052-1.055 1.052-0.571 0-1.042-0.47-1.042-1.052l-0.009-2.32h-0.757c-0.622 0-1.124-0.501-1.124-1.125v-6.807zM2.357 5.502c-0.582 0-1.053 0.471-1.053 1.042v4.396c0 0.583 0.471 1.052 1.053 1.052s1.042-0.47 1.042-1.052v-4.396c0-0.571-0.468-1.042-1.042-1.042zM13.222 5.328h-9.454c0-1.625 0.972-3.036 2.413-3.771l-0.727-1.338c-0.041-0.072-0.021-0.164 0.051-0.205 0.071-0.031 0.164-0.011 0.205 0.062l0.735 1.349c0.625-0.277 1.32-0.43 2.055-0.43s1.43 0.153 2.055 0.429l0.735-1.349c0.041-0.072 0.134-0.092 0.205-0.062 0.072 0.041 0.092 0.133 0.051 0.205l-0.727 1.338c1.432 0.736 2.403 2.147 2.403 3.772zM6.741 3.223c0-0.215-0.173-0.399-0.397-0.399-0.216 0-0.389 0.184-0.389 0.399 0 0.214 0.173 0.398 0.389 0.398 0.224 0.001 0.397-0.183 0.397-0.398zM11.045 3.223c0-0.215-0.173-0.399-0.389-0.399-0.225 0-0.397 0.184-0.397 0.399 0 0.214 0.173 0.398 0.397 0.398 0.216 0.001 0.389-0.183 0.389-0.398zM14.643 5.502c-0.573 0-1.042 0.46-1.042 1.042v4.396c0 0.583 0.469 1.052 1.042 1.052 0.582 0 1.053-0.47 1.053-1.052v-4.396c-0.001-0.582-0.471-1.042-1.053-1.042z" fill="#fff"/>
                </svg>
             </span>
             <span>Android App</span>
          </a>
          <a class="btn app-link">
             <span class="icon icon_tv-app">
                <svg fill="#494c4e" width="20px" height="20px" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMin" class="jam jam-screen-f">
                   <path d="M3 .565h14a3 3 0 0 1 3 3v9a3 3 0 0 1-3 3H3a3 3 0 0 1-3-3v-9a3 3 0 0 1 3-3zm4 16h6a1 1 0 0 1 0 2H7a1 1 0 0 1 0-2z"/>
                </svg>
             </span>
             <span>TV App</span>
          </a>
       </div>
       <a class="header__feedback feedback-btn">
          <span class="icon icon_email">
             <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" xml:space="preserve">
                <circle style="fill:#23252b;" cx="256" cy="256" r="256"/>
                <g>
                   <path style="fill:#f7cb2f;" d="M400.272,356.08H112.048v-205.6h288.24v205.6H400.272z M128.048,340.08h256.24v-173.6h-256.24
                      V340.08z"/>
                   <polygon style="fill:#f7cb2f;" points="256.176,279.824 115.824,192.704 124.256,179.104 256.144,260.976 388.032,178.464
                      396.528,192.032 	"/>
                </g>
                <rect x="342.548" y="225.448" transform="matrix(-0.7863 0.6178 -0.6178 -0.7863 807.8576 308.6862)" style="fill:#f7cb2f;" width="16" height="137.196"/>
                <polygon style="fill:#f7cb2f;" points="126.032,352.944 113.424,343.056 198.208,235.168 210.8,245.04 "/>
             </svg>
          </span>
       </a>
        {% if request.user.is_authenticated %}
        <div class="header__profile">
            <a class="header__profile-main" href="#" data-content="dropdown-toggle">
                <img class="header__profile-photo" src="{{ request.user.profile.photo.url }}">
                <span class="header__profile-user">{{ user.username }}</span>
            </a>
            <div class="header__profile-menu" data-content="dropdown-menu">
                <a href="{% url 'user:profile' %}">Профиль</a>
                <a href="{% url 'user:logout' %}">Выйти</a>
            </div>
        </div>
        {% else %}
        <div class="header__login"><a class="btn btn_yellow" href="{% url 'user:login' %}">Войти</a></div>
        {% endif %}
    </header>

    {% block content %}

    {% endblock%}
    <footer class="footer hide-lg">
       <nav class="footer__nav">
          <a class="nav-link active" href="{% url 'movie:home' %}">
             <span class="icon icon_home">
                <svg width="24px" height="24px" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
                   <path fill="#494c4e" d="M512 128 128 447.936V896h255.936V640H640v256h255.936V447.936z"/>
                </svg>
             </span>
             <span>Главная</span>
          </a>
          <a class="nav-link"href="{% url 'movie:full_categories' %}">
             <span class="icon icon_catalog">
                <svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" mirror-in-rtl="true">
                   <path fill="#494c4e" d="M6 18H1a1 1 0 0 1-1-1v-5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1zM17 18h-5a1 1 0 0 1-1-1v-5a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1zM6 7H1a1 1 0 0 1-1-1V1a1 1 0 0 1 1-1h5a1 1 0 0 1 1 1v5a1 1 0 0 1-1 1zM17.708 5.24l-3.535 3.535a1 1 0 0 1-1.414 0L9.224 5.24a1 1 0 0 1 0-1.413L12.76.292a1 1 0 0 1 1.414 0l3.535 3.535a1 1 0 0 1-.002 1.414z"/>
                </svg>
             </span>
             <span>Каталог</span>
          </a>
          <a class="nav-link" href="{% url 'movie:favorite_list' %}">
             <span class="icon icon_tv">
                <svg fill="#494c4e" width="20px" height="20px" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMin" class="jam jam-screen-f">
                   <path d="M3 .565h14a3 3 0 0 1 3 3v9a3 3 0 0 1-3 3H3a3 3 0 0 1-3-3v-9a3 3 0 0 1 3-3zm4 16h6a1 1 0 0 1 0 2H7a1 1 0 0 1 0-2z"/>
                </svg>
             </span>
             <span>Мой MovieLab</span>
          </a>
          <a class="nav-link" href="{% url 'user:profile' %}">
             <span class="icon icon_settings">
                <svg fill="#494c4e" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                   <path d="M4,13.743l-1,.579a1,1,0,0,0-.366,1.366l1.488,2.578a1,1,0,0,0,1.366.366L6.5,18.05a1.987,1.987,0,0,1,1.986,0l.02.011a1.989,1.989,0,0,1,1,1.724V21a1,1,0,0,0,1,1h3a1,1,0,0,0,1-1V19.782a1.985,1.985,0,0,1,.995-1.721l.021-.012a1.987,1.987,0,0,1,1.986,0l1.008.582a1,1,0,0,0,1.366-.366l1.488-2.578A1,1,0,0,0,21,14.322l-1-.579a1.994,1.994,0,0,1-1-1.733v-.021a1.991,1.991,0,0,1,1-1.732l1-.579a1,1,0,0,0,.366-1.366L19.876,5.734a1,1,0,0,0-1.366-.366L17.5,5.95a1.987,1.987,0,0,1-1.986,0L15.5,5.94a1.989,1.989,0,0,1-1-1.724V3a1,1,0,0,0-1-1h-3a1,1,0,0,0-1,1V4.294A1.856,1.856,0,0,1,8.57,5.9l-.153.088a1.855,1.855,0,0,1-1.853,0L5.49,5.368a1,1,0,0,0-1.366.366L2.636,8.312A1,1,0,0,0,3,9.678l1,.579A1.994,1.994,0,0,1,5,11.99v.021A1.991,1.991,0,0,1,4,13.743ZM12,9a3,3,0,1,1-3,3A3,3,0,0,1,12,9Z"/>
                </svg>
             </span>
             <span>Настройки</span>
          </a>
       </nav>
    </footer>
 <script defer="defer" src="{% static 'js/user_profile.js' %}"></script>
</body>
</html>

movie/templates/movie/favorites.html
{% extends 'movie/base.html' %}
{% load static %}

{% block content %}
<main class="main">
  <div class="favorites">
    <div class="favorites-nav">
        <a class="favorites-link active" href="#">Закладки</a>
        <a class="favorites-link" href="#">История</a>
        <a class="favorites-link" href="#">Рейтинг</a>
        <a class="favorites-link" href="#">Мои коллекции</a>
        <a class="favorites-link" href="#">Избранные коллекции</a>
    </div>
      {% if new %}
        <div class="favorites__list">
            {% for movie in new %}
            <a class="movie-poster" href="{% url 'movie:movie' movie.pk %}">
                <div class="movie-poster__main">
                  <div class="movie-poster__img">
                      {% if movie.poster_url %}
                        <img src="{{ movie.poster_url_preview.url }}" alt="{{ movie.title }}">
                      {% endif %}
                  </div>
                    <span class="movie-poster__rating">5.7</span><span class="movie-poster__quality">HD</span>
                </div>
                <p class="movie-poster__title">{{ movie.title|truncatewords:50 }}</p>
            </a>
            {% endfor %}
        </div>
      {% else %}
        <div class="favorites__error">
          <h4 class="alert-heading">Тут пока ничего нет</h4>
             {% if user.is_authenticated %}
            <a class="btn btn_yellow" href="{% url 'movie:home' %}">Перейти в каталог</a>
            {% else %}
            <a class="btn btn_yellow" href="{% url 'user:login' %}">Войти</a>
            {% endif %}
        </div>
      {% endif %}
  </div>
</main>
{% endblock%}

movie/templates/movie/full-categories.html
{% extends 'movie/base.html' %}
{% load static %}

{% block content %}
    <main class="main">
      <h2 class="poster-slider-title">Коллекции</h2>
      <div class="catalog-slider">
        <div class="swiper swiper_movie" data-jsclass="swiperMovieCollection">
          <div class="swiper-wrapper">
              {% for category in categories %}
                <div class="swiper-slide">
                    <a class="movie-category" href="{{ category.pk }}">
                        {% if category.poster %}
                        <img class="movie-category__img" src="{{ category.poster.url }}" alt="{{ category.category }}">
                        {% endif %}
                        <p class="movie-category__title">{{ category.category|truncatewords:50 }}</p>
                    </a>
                </div>
              {% endfor %}
          </div>
          <div class="swiper-button-next"></div>
          <div class="swiper-button-prev"></div>
        </div>
      </div>
    </main>
{% endblock%}

movie/templates/movie/movies-list.html
{% extends 'movie/base.html' %}
{% load static %}

{% block content %}
<main class="main">
    {% include 'movie/blocks/movie-cards.html' %}
</main>

{% endblock%}

movie/templates/movie/nav-top.html
<div class="top-menu-slider">
  <div class="swiper swiper_movie" data-jsclass="swiperMovie">
     <div class="swiper-wrapper">
        <div class="swiper-slide"><a class="btn btn_yellow btn_big"  href="{% url 'movie:random_movies' %}">Мне повезет</a></div>
         {% for genre in genres %}
            <div class="swiper-slide"><a href="{% url 'movie:movies_genre' genre.pk %}" class="btn btn_gray btn_big">{{ genre|capfirst }}</a></div>
         {% endfor %}
     </div>
     <div class="swiper-button-next"></div>
     <div class="swiper-button-prev"></div>
  </div>
</div>